### ISSUE TITLE
Upgrade the  eslint-plugin-perfectionist to v2

### ISSUE THREAD

**Issue by dipiash** [dipiash/eslint-plugin-nimbus-clean#12]
**Is your feature request related to a problem? Please describe.**
Currently the `eslint-plugin-perfectionist` is ^1.5.1

**Describe the solution you'd like**
Need to upgrade to ^2.2.0 or above. See [changelog](https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/changelog.md).

**Additional context**
See the contributing [guide](https://github.com/dipiash/eslint-plugin-nimbus-clean/blob/main/CONTRIBUTING.md).

**Comment by Malay-dev** [comment]
Hey @dipiash, I would like to work on this issue. Please assign it to me....

**Comment by dipiash** [comment]
Hi, @Malay-dev! 

Done it. Thank you🙏
