### ISSUE TITLE
Add instructions for pnpm

### ISSUE THREAD

**Issue by dipiash** [dipiash/eslint-plugin-nimbus-clean#16]
**Is your feature request related to a problem? Please describe.**
Currently repository has instructions only for `npm`

**Describe the solution you'd like**
Improve Readme and add a section for `pnpm`

**Additional context**
See the popular repositories where describe `npm` and `pnpm` sections

See the contributing [guide](https://github.com/dipiash/eslint-plugin-nimbus-clean/blob/main/CONTRIBUTING.md).

**Comment by Vidhanvyrs** [comment]
hey @dipiash please assign this issue to me i think i can help you with it🚀

**Comment by dipiash** [comment]
Hey @Vidhanvyrs!

Done it

**Comment by dipiash** [comment]
Hi, @Vidhanvyrs!

Do you want to continue this issue?

**Comment by dipiash** [comment]
Hi, @Bhavya-Chawla!

Thank you for yours interest. Let's try to get answer from @Vidhanvyrs because @Vidhanvyrs was first 🙏

**Comment by Bhavya-Chawla** [comment]
Sure. Just ping me if @Vidhanvyrs don't want to continue. Thanks :)

**Comment by Vidhanvyrs** [comment]
hey @dipiash i am working on this issue surely will generate a PR by today
