### ISSUE TITLE
Add link to LICENSE into Readme file

### ISSUE THREAD

**Issue by dipiash** [dipiash/eslint-plugin-nimbus-clean#20]
**Is your feature request related to a problem? Please describe.**
The repository has a license file but Readme doesn't contain the link on it

**Describe the solution you'd like**
Add section with title `License` and with content MIT is a link to license file

**Additional context**

See the contributing [guide](https://github.com/dipiash/eslint-plugin-nimbus-clean/blob/main/CONTRIBUTING.md).

**Comment by a-arham-x** [comment]
Hi @dipiash , kindly assign this issue to me. I want to work with it.

**Comment by dipiash** [comment]
Hi @a-arham-x!

Thank you. Done ✔️

**Comment by imrtls00** [comment]
Hi @dipiash , @a-arham-x
It's Done :P
