### ISSUE TITLE
Shorten installation instructions

### ISSUE THREAD

**Issue by areebniyas** [dipiash/eslint-plugin-nimbus-clean#27]
**Is your feature request related to a problem? Please describe.**
The installation instructions with the recently added `yarn` and `pnpm` instructions seem quite long and unnecessarily long to read.

**Describe the solution you'd like**
Improve Readme by avoiding redundancies. Sample of what the instructions could look like for the first part:

```sh
npm i eslint --save-dev
npm i typescript
# Or run this to use yarn
yarn add eslint --dev
yarn add typescript
# Or run this to use pnpm
pnpm add eslint --save-dev
pnpm add typescript
```

This way we can shorten it and keep it concise instead of having different headings and topics for `yarn` and `pnpm`.

**Additional context**
Would love to hear any feedback on this matter.

**Comment by dipiash** [comment]
Hi, @areebniyas!

I think it's a good idea 👍
