### ISSUE TITLE
Add "Contributors" section

### ISSUE THREAD

**Issue by dipiash** [dipiash/eslint-plugin-nimbus-clean#48]
**Is your feature request related to a problem? Please describe.**
Currently the readme files doesen't contain the "Contributors" section

**Describe the solution you'd like**
Title: `Contributors`
Description: `Thanks go to these wonderful people:`
List of contributors

If it possible to make it automate for adding in README. It will be great!

**Additional context**
See the contributing [guide](https://github.com/dipiash/eslint-plugin-nimbus-clean/blob/main/CONTRIBUTING.md).

**Comment by Aditya-Armal** [comment]
![image](https://github.com/dipiash/eslint-plugin-nimbus-clean/assets/20648225/1a6c630d-b34b-4b87-a55a-6ac2ec8c151f)

The above pull request would automatically display all contributors in Readme file as shown above.

**Comment by dipiash** [comment]
Thank you @Aditya-Armal
